### ISSUE TITLE
The Button to select a specific pyinstaller targets the icon field not the pyinstaller one

### ISSUE THREAD

**Issue by andrewmk** [PySimpleGUI/psgcompiler#1]
In the definition of the layout:

```
...
              [sg.Text('Icon: ', s=20), sg.Input(key='-ICONFILE-', expand_x=True, enable_events=True),
                 sg.FileBrowse(target='-ICONFILE-', file_types=(("Icon Files", "*.ico"),))],
                [sg.Text('Optional specific pyinstaller: ', s=20), sg.Input(key='-PYINSTALLER-', expand_x=True),
                 sg.FileBrowse(target='-ICONFILE-', file_types=(("Icon Files", "*.ico"),))],
...
```
the FileBrowse button for picking a pyinstaller executable should target the '-PYINSTALLER-' Input field and should probably have filetypes as something like ("All files", "\*.\*").

**Comment by PySimpleGUI** [comment]
I'll have Tanay give it a look!  Thank you!

**Comment by PySimpleGUI** [comment]
The fix is both here on GitHub and was released to PyPI as well in Dec 2021 so closing this issue.  If there's still a problem, by all means re-open it.

![image](https://user-images.githubusercontent.com/46163555/160501063-3152e988-9e5f-448e-a3be-6a0c0af5e647.png)
