### ISSUE TITLE
Can't import package 'pytube'

### ISSUE THREAD

**Issue by Trolann** [PySimpleGUI/psgcompiler#4]
I've been trying to get PyTube to import into my exe. I have import pytube at the top of the script and when trying to run the file I get a modulenotfound error.

Here's the snippet from PSGCompiler:

```
123 WARNING: Unable to copy metadata for pytube: The 'pytube' distribution was not found and is required by the application
123 WARNING: collect_data_files - skipping data collection for module 'pytube' as it is not a package.
124 WARNING: collect_dynamic_libs - skipping library collection for module 'pytube' as it is not a package.
181 INFO: Determining a mapping of distributions to packages...
7343 WARNING: Unable to determine requirements for pytube: The 'pytube' distribution was not found and is required by the application
```

pytube is a package, how do I get psgcompiler to see it?

**Comment by DevStrom20** [comment]
More details, please. Coding Interpreter, and what if do you installed the lib of pytube, for example "pip install pytube".
